---
title: Tiago Loriato
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tloriatosimoes@gmail.com
description: A collection of notes, researches, projects, and essays.
baseurl: ''
url: https://tloriato.github.io
permalink: pretty
social_sites:
  github: tloriato
  twitter: tiagoloriato
  linkedin: tloriato
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-analytics
kramdown:
  input: GFM
  parse_block_html: true
highlighter: rouge
future: false
exclude:
- vendor